version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "2.7"
  commands:
      - pip install --upgrade pip setuptools wheel
      - cd ${READTHEDOCS_PROJECT}/doc && pip install -r requirements.txt
      - cd ${READTHEDOCS_PROJECT}/doc && make html
      - mkdir _readthedocs
      - cp -rv ${READTHEDOCS_PROJECT}/doc/_build/html _readthedocs/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: ${READTHEDOCS_PROJECT}/doc/conf.py

python:
   install:
   - requirements: ${READTHEDOCS_PROJECT}/docs/requirements.txt

